[GS-1]Create skeleton of project for desktop
MaksymTimofeev/Gamers-shop pull request #1
Opened 2024-02-04 17:42 UTC by MaksymTimofeev

2024-03-04 12:03 UTC, MaximDrobchak commented
![dfg346463456](https://github.com/MaksymTimofeev/Gamers-shop/assets/33839939/0fbd575c-68fd-45c4-a4d2-db9175af8b45)
Can't resolve this margin for example

2024-03-04 15:21 UTC, MaksymTimofeev commented
![отступы](https://github.com/MaksymTimofeev/Gamers-shop/assets/94307941/0fd6dbdc-63fd-44ae-b3f4-9769f9818597)
I can't indent the left margin

2024-03-04 15:26 UTC, MaksymTimofeev commented
![При маштабировании сдвигаются блоки](https://github.com/MaksymTimofeev/Gamers-shop/assets/94307941/16d53c9d-21b5-45e0-b0d5-cc346931e5d8)
Blocks move when scaling

2024-03-04 17:56 UTC, MaximDrobchak commented on css/style.css
> +  margin-bottom: 50px;
👍

2024-03-04 18:00 UTC, MaximDrobchak requested changes

2024-03-04 18:00 UTC, MaximDrobchak commented on img/Rectangle.jpg
Remove this image it's dublicate and image should not be in the skeleton

2024-03-04 18:00 UTC, MaximDrobchak commented on img/img1.jpg
Remove this image, The picture should not be in the skeleton

2024-03-04 18:00 UTC, MaximDrobchak commented on img/63b3e5defc6c0510d0dc78a26ec1df10.png
Remove this image, The picture should not be in the skeleton

2024-03-04 18:04 UTC, MaximDrobchak commented
@MaksymTimofeev  Remove this screenshot, it is not needed
![image](https://github.com/MaksymTimofeev/Gamers-shop/assets/33839939/70c4e434-9745-4522-8c42-20fdaae82c11)

2024-03-06 11:14 UTC, MaximDrobchak commented
@MaksymTimofeev  Nice job

2024-03-06 11:14 UTC, MaximDrobchak approved these changes

2024-03-06 11:15 UTC, merged